### ISSUE TITLE
When saving a resource price is lost

### ISSUE THREAD

**Issue by Ratmil** [Ratmil/payperdownload#2]
When saving a resource in back-end price is lost when the resource is loaded again on the same page. Price is actually saved but is not loaded back.

**Comment by obuisard** [comment]
It also looses enabled, expiration, max downloads and shared.
I confirm that the items are saved in the backend.
After further testing, it appears that all numbers and spaces are removed from all values of the form.

**Comment by obuisard** [comment]
I have found the problem. It's caused by the use of JFactory::getApplication()->input->getWord(), introduced in 6.0.
getWords() only allows characters a-z, and underscores. 
I am surveying the code right now and will produce a PR once I am done.

**Comment by Ratmil** [comment]
Wow!! Thanks.

**Comment by obuisard** [comment]
PR #4 fixes the issue.

You are welcome Ratmil :-)
